rubenvoss/GoClimb

app/views/shared/_navbar.html.erb

added logo to navbar

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss

added IBM Plex Sans and colors

---

app/controllers/profiles_controller.rb
app/views/profiles/show.html.erb
config/routes.rb

Very fancy view page for profiles#show

Profile show

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/views/profiles/new.html.erb

added red and blue buttons

---

app/controllers/profiles_controller.rb
app/views/profiles/_form.html.erb
app/views/profiles/new.html.erb
app/views/profiles/show.html.erb
config/routes.rb

Edit profile directly in showpage (we should replace that with js)

Profile edit

---

app/controllers/reviews_controller.rb
app/models/profile.rb
app/views/profiles/show.html.erb
app/views/reviews/new.html.erb
config/routes.rb

Review actions work (new, create & destroy). I didn't add edit or update options, since I figured if you mistype or change your mind, you just delete your review instead of updating. You can only delete it when you wrote it, otherwise you get a link to leave a review instead :)

Reviews index

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Login, register forms container and buttons

---

app/controllers/pages_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/search_controller.js
app/views/pages/_list.html.erb
app/views/pages/search.html.erb

displays search results

---

Gemfile
app/assets/stylesheets/application.scss
app/controllers/pages_controller.rb
app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/search_controller.js
app/views/pages/_list.html.erb
app/views/pages/search.html.erb
package.json
yarn.lock

Date picker

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_message.scss
app/controllers/messages_controller.rb
app/controllers/profiles_controller.rb
app/javascript/controllers/chatroom_subscription_controller.js
app/models/message.rb
app/views/chatrooms/show.html.erb
app/views/messages/_message.html.erb
app/views/profiles/_form.html.erb
db/seeds.rb

If user has profile, chatbox displays name and picture - otherwise user-email.

Chatbox styling

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/search_bottom.scss
app/controllers/chatrooms_controller.rb
app/views/chatrooms/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_search_bottom.html.erb
config/routes.rb

navbar with buttons, searchbar at bottom, scss, messages page

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/search_bottom.scss
app/controllers/chatrooms_controller.rb
app/views/chatrooms/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_search_bottom.html.erb
config/routes.rb
db/seeds.rb

added some seeds, you can now search for country and will get the crags as a result as well

---

app/models/profile.rb

validates profile photo

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_profile.scss
app/views/profiles/show.html.erb

Profile frontend

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

removed svg, inserted div into navbar

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_search_results.scss
app/controllers/crags_controller.rb
app/javascript/controllers/save_dates_controller.js
app/javascript/controllers/search_controller.js
app/views/crags/_header.html.erb
app/views/crags/show.html.erb
app/views/pages/_list.html.erb
app/views/pages/search.html.erb

https://user-images.githubusercontent.com/105738004/188271567-d2c59017-39e0-4e30-87fe-7cf7b58f5d89.mov

fixed the scroll on the search page, persisting data from search page to crag#show

---

app/views/profiles/show.html.erb
db/seeds/04_seed_profiles.rb
db/seeds/06_review_seeds.rb

Not working yet, need some help ;)

seeds not working due to dependencies

---

app/views/profiles/show.html.erb
db/seeds/00_cleaning_db.rb
db/seeds/06_review_seeds.rb
db/seeds/07_trip_seeds.rb

for seeding reviews, it's looking for profile id starting at 1, which it doesn't find

Trip seeds

---

app/controllers/trips_controller.rb
app/views/profiles/_trip_form.html.erb
app/views/profiles/show.html.erb

Functionality works, frontend looks shit (we need js, I can fix it tomorrow :))

edit trip function works

---

app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_profile.scss
app/assets/stylesheets/components/_text_styling_titles_headers.scss
app/controllers/profiles_controller.rb
app/controllers/reviews_controller.rb
app/models/profile.rb
app/models/review.rb
app/views/profiles/_form.html.erb
app/views/profiles/show.html.erb
app/views/reviews/new.html.erb
db/migrate/20220829123557_create_profiles.rb
db/schema.rb
db/seeds/02_seed_countries_and_crags.rb
db/seeds/03_seed_users.rb
db/seeds/04_seed_profiles.rb
db/seeds/05_chatroom_seed.rb
db/seeds/06_review_seeds.rb

- did a lot of profile styling to get it looking like in figma
- showing a black line if there are reviews, if not showing nothing
- reviews have a blue background now
- changed font sizing of t1
- added age to our database (we might have to drop heroku db)
- changed review, so that you only need comment
- got the trip seeds working - date is a Date instance!!!
- added bio to the profile seeds
- added jasmien and ruben to profiles
- removed rating from review seeds
- added bangs to our seeds, so that the seed crashes if something is not there

sorry, this should be 10 pull requests 💀 

---

app/controllers/crags_controller.rb
app/javascript/controllers/map_controller.js
app/views/crags/show.html.erb
db/seeds/08_activity_seeds.rb

map has activities on it

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/controllers/crags_controller.rb
app/javascript/controllers/map_controller.js
app/views/crags/_info_window.html.erb

Info windows

---

app/controllers/profiles_controller.rb
app/javascript/controllers/edit_profile_controller.js
app/javascript/controllers/index.js
app/views/profiles/_form.html.erb
app/views/profiles/_profile_infos.html.erb
app/views/profiles/show.html.erb

Sorry, tried making a video, it worked - but now it's too big for upload xD

Edit profile

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_text_styling_titles_headers.scss
app/views/crags/partials/_local_climbers.html.erb
app/views/crags/partials/_travelling_climbers.html.erb
app/views/crags/show.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_profile_cards.html.erb

Crag show profiles cards

---

app/controllers/reviews_controller.rb
app/views/profiles/partials/_reviews.html.erb

Ruuuuuuuben, please fix the frontend <3

delete link works, frontend needs to be fixed

---

app/assets/stylesheets/components/_text_styling_titles_headers.scss
app/views/shared/_profile_cards.html.erb

card layout

---

db/seeds/08_activity_seeds.rb

Activity seeds

---

app/views/chatrooms/index.html.erb

made chatroom links blue button

---

app/views/profiles/partials/_trips.html.erb
app/views/trips/_trip_info.html.erb

trip add button only on own profile page

---

.github/workflows/rubyonrails.yml

automated testing on github servers

add continuous integration for goclimb

---

run

[Guide on how to use the script](https://github.com/rubenvoss/devops-rails/blob/main/bash_script.md)

add run script

---

db/seeds/07_trip_seeds.rb

remove name, add id
